### PR TITLE
Fixes #90: Kerning adjustment being performed on device control function \X'string'

### LINKED ISSUE #90: Kerning adjustment being performed on device control function \X'string'
When using `\X'string'`, if any of the characters in `string` have kerning pairs, the final text layout is affected. `\Y` does not have this issue. This may be more or less pronounced, depending on the font being used. For example, font "TexGyre Schola" has a kerning adjustment for the pair "et", meaning that `\X'SetColor: ...'` will affect the text positioning, if that particular font is active. The following example purposely uses characters which make the problem easier to notice:

```
.do xflag 3
.mediasize 100p 100p
.po 10p
.ll 40p
.\" example device control function with kerning pairs:
.ds T VAVA: WaWa
.\" PROBLEM:
\X'\*T'A \X'\*T'B \X'\*T'C\p
.\" OK:
\YTA \YTB \YTC\p
.
.\" verify \Z'string' is not affected by the fix:
.kern 0
VA Wa                \" kern off: reference
.br
.kern 1
VA Wa                \" kern on
.br
\Z'VA Wa'            \" same result
.br
```

The result can be seen in attached file [kern_problem.pdf](https://github.com/n-t-roff/heirloom-doctools/files/3708337/kern_problem.pdf).

The following fix seems to solve this problem, hopefully without creating any new problems. In file `troff/troff.d/t6.c`, modify line 471:

```
- if (!kern || ismot(c) || ismot(e) || html)
+ if (!kern || ismot(c) || ismot(e) || html || iszbit(c) || iszbit(e))
```

The result after the fix can be seen in attached file [kern_problem_after_fix.pdf](https://github.com/n-t-roff/heirloom-doctools/files/3708340/kern_problem_after_fix.pdf).

The example input includes the line `\Z'VA Wa'` to verify that the fix does not break kerning in zero width/height text. Maybe there are other cases which would need testing.

### PR DESCRIPTION
**Pull request by mircea3**
This changes one line (plus some white space). 
The before/after result can be seen in pdf files attached to issue #90.

### CODE REVIEW

**Comment by Alhadis** [comment]
> plus some white space

Was that accidental? What editor are you using?

**Comment by mircea3** [comment]
I use emacs. My personal preference is for the editor to strip all trailing space when saving, making sure new files are clean, and older files gradually becoming cleaner. However, that is a personal preference; if others prefer the trailing spaces I could put them back (for this project).

**Comment by Alhadis** [comment]
It's not about preference, it's about keeping revision history clean and atomic. This sort of cleanup can always be done in a later PR, if you're so inclined (and I believe @n-t-roff may wish to add an `.editorconfig` or `.dir.locals.el` file or something to prevent bikesheddy stuff like this arising in future... 😉)

**Comment by n-t-roff** [comment]
I have to agree to @Alhadis , no unnecessary changes please. @Alhadis : Using `.editorconfig` is a good hint.

**Pull request merged**
